apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-pod
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-pod
    spec:
      volumes:
        - name: {{.Release.Name}}-configmap-volume
          configMap:
            name: {{.Release.Name}}-configmap
      containers:
        - name: {{.Release.Name}}-app
          image: larskj/xfe:v13
          imagePullPolicy: Never
          ports:
            - containerPort: 8887
              name: net
            - containerPort: 8888
              name: api
            - containerPort: 8889
              name: monitoring
          env:
            - name: arne
              value: anka
            - name: pelle
              value: fant
          volumeMounts:
            - name: {{.Release.Name}}-configmap-volume
              mountPath: /etc/config
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
          livenessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5

