apiVersion: apps/v1
kind: Deployment
metadata:
  name: xfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xfe-pod
  template:
    metadata:
      labels:
        app: xfe-pod
    spec:
      containers:
        - name: xfe-app
          image: larskj/xfe:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8887
              name: net
            - containerPort: 8888
              name: api
            - containerPort: 8889
              name: monitoring
          resources:
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5

