apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: xfe-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xfe
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
      type: Resource
