apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service-hazelcast
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{.Release.Name}}-pod
  ports:
    - port: 5701
      name: hazelcast
      protocol: TCP
      targetPort: hazelcast

