apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-{{.Release.Name}}-config
  namespace: default
data:
  config.yaml: |-
{{ printf "config/%s.yaml" .Release.Name | .Files.Get | indent 4}}
