apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}-config
  namespace: {{ .Release.Namespace}}
data:
  config.yaml: |-
{{ printf "config/%s.yaml" .Release.Name | .Files.Get | indent 4}}
