apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}-{{.Release.Name}}-pod
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-{{.Release.Name}}-pod
    spec:
      containers:
        - name: {{.Chart.Name}}-{{.Release.Name}}-app
          image: {{.Values.image.repository}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 5701
              name: hazelcast
            - containerPort: 8888
              name: api
            - containerPort: 8889
              name: monitoring
          volumeMounts:
            - mountPath: /opt/app/config.yaml
              name: {{.Chart.Name}}-{{.Release.Name}}-config-volume
              subPath: config.yaml
          env:
            - name: disco_dns
              value: {{.Chart.Name}}-{{.Release.Name}}-service-hazelcast.{{.Release.Namespace}}.svc.cluster.local
          livenessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: monitoring
            timeoutSeconds: 5
      volumes:
        - name: {{.Chart.Name}}-{{.Release.Name}}-config-volume
          configMap:
            name: {{.Chart.Name}}-{{.Release.Name}}-config
