apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{.Release.Name}}-service
spec:
  selector:
    app: {{.Chart.Name}}-{{.Release.Name}}-pod
  ports:
    - port: 8080
      name: api
      protocol: TCP
      targetPort: api
    - port: 8081
      name: monitoring
      protocol: TCP
      targetPort: monitoring
  type: LoadBalancer
