# Default values for xfe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: larskj/hcast:v13
  pullPolicy: Never

resources:
   limits:
    cpu: 500m
    memory: 256Mi
   requests:
    cpu: 500m
    memory: 256Mi
